"""``backend.app.api.v1.endpoints.industry`` 包入口。

包含 11 个 FastAPI 路由 handler（行业成分股 + 偏好 + 趋势 + intelligence + network + health），
重型业务逻辑分散在 ``heatmap_service`` / ``ranking_service`` / ``trend_service`` /
``preferences_service``，共享单例与缓存仍在 ``_helpers``。
"""

# --- helpers / 模块级状态 / 数据 ---
from ._helpers import (
    DEFAULT_ALERT_THRESHOLDS,
    INDUSTRY_ETF_MAP,
    _akshare_provider,
    _attach_execution_metadata,
    _build_execution_metadata,
    _build_full_industry_stock_response,
    _build_quick_industry_stock_response,
    _build_stock_responses,
    _build_trend_summary_from_stock_rows,
    _coerce_trend_alignment_stock_rows,
    _count_quick_stock_detail_fields,
    _endpoint_cache,
    _format_storage_size,
    _get_endpoint_cache,
    _get_or_create_provider,
    _get_parity_cache,
    _get_stale_endpoint_cache,
    _get_stale_parity_cache,
    _get_stock_build_status,
    _get_stock_cache_keys,
    _get_stock_status_key,
    _heatmap_history,
    _heatmap_history_lock,
    _industry_analyzer,
    _leader_scorer,
    _load_trend_alignment_stock_rows,
    _model_to_dict,
    _parity_cache,
    _promote_detail_ready_quick_rows,
    _resolve_industry_profile,
    _resolve_symbol_with_provider,
    _schedule_full_stock_cache_build,
    _set_endpoint_cache,
    _set_parity_cache,
    _set_stock_build_status,
    _should_align_trend_with_stock_rows,
    _stocks_full_build_executor,
    _stocks_full_build_inflight,
    _stocks_full_build_lock,
    _stocks_full_build_status,
    get_industry_analyzer,
    get_leader_scorer,
    industry_preferences_store,
    logger,
)
from .heatmap_service import (
    _build_curated_fallback_rows,
    _build_industry_events,
    _build_industry_intelligence_result,
    _build_industry_network_result,
    _build_rows_from_heatmap_history,
    _classify_industry_lifecycle,
    _cosine_similarity,
    _load_heatmap_history_from_disk,
    _map_industry_etfs,
    _resolve_intelligence_rows_from_fallback,
    _trim_heatmap_history_payload,
)

# --- 路由 handler / router ---
from .routes import (
    export_industry_preferences,
    get_industry_intelligence,
    get_industry_network,
    get_industry_preferences,
    get_industry_stock_build_status,
    get_industry_stocks,
    get_industry_trend,
    health_check,
    import_industry_preferences,
    router,
    stream_industry_stock_build_status,
    update_industry_preferences,
)

# --- Schema re-export（测试构造 mock 时使用）---
from backend.app.schemas.industry import (  # noqa: E402
    HeatmapDataItem,
    HeatmapHistoryItem,
    IndustryPreferencesResponse,
    IndustryStockBuildStatusResponse,
    IndustryTrendResponse,
    StockResponse,
)


__all__ = [
    "router",
    # 模块级状态
    "_endpoint_cache",
    "_parity_cache",
    "_heatmap_history",
    "_heatmap_history_lock",
    "_stocks_full_build_inflight",
    "_stocks_full_build_lock",
    "_stocks_full_build_status",
    "_stocks_full_build_executor",
    "_industry_analyzer",
    "_leader_scorer",
    "_akshare_provider",
    "INDUSTRY_ETF_MAP",
    "DEFAULT_ALERT_THRESHOLDS",
    "logger",
    # cache helpers
    "_get_endpoint_cache",
    "_set_endpoint_cache",
    "_get_stale_endpoint_cache",
    "_get_parity_cache",
    "_set_parity_cache",
    "_get_stale_parity_cache",
    "_get_stock_cache_keys",
    "_get_stock_status_key",
    "_get_stock_build_status",
    "_set_stock_build_status",
    # builders
    "_build_full_industry_stock_response",
    "_build_quick_industry_stock_response",
    "_build_stock_responses",
    "_build_curated_fallback_rows",
    "_build_industry_events",
    "_build_industry_intelligence_result",
    "_build_industry_network_result",
    "_build_rows_from_heatmap_history",
    "_build_trend_summary_from_stock_rows",
    "_build_execution_metadata",
    "_attach_execution_metadata",
    "_classify_industry_lifecycle",
    "_coerce_trend_alignment_stock_rows",
    "_cosine_similarity",
    "_count_quick_stock_detail_fields",
    "_format_storage_size",
    "_load_heatmap_history_from_disk",
    "_load_trend_alignment_stock_rows",
    "_map_industry_etfs",
    "_model_to_dict",
    "_promote_detail_ready_quick_rows",
    "_resolve_industry_profile",
    "_resolve_intelligence_rows_from_fallback",
    "_resolve_symbol_with_provider",
    "_schedule_full_stock_cache_build",
    "_should_align_trend_with_stock_rows",
    "_trim_heatmap_history_payload",
    # singletons
    "get_industry_analyzer",
    "get_leader_scorer",
    "_get_or_create_provider",
    "industry_preferences_store",
    # routes
    "export_industry_preferences",
    "get_industry_intelligence",
    "get_industry_network",
    "get_industry_preferences",
    "get_industry_stock_build_status",
    "get_industry_stocks",
    "get_industry_trend",
    "health_check",
    "import_industry_preferences",
    "stream_industry_stock_build_status",
    "update_industry_preferences",
    # schemas
    "HeatmapDataItem",
    "HeatmapHistoryItem",
    "IndustryPreferencesResponse",
    "IndustryStockBuildStatusResponse",
    "IndustryTrendResponse",
    "StockResponse",
]
