export const STOCK_DATABASE = {
    // 1. 指数 (Indices)
    '^GSPC': { en: 'S&P 500', cn: '标普500', type: 'index' },
    '^DJI': { en: 'Dow Jones', cn: '道琼斯', type: 'index' },
    '^IXIC': { en: 'NASDAQ Composite', cn: '纳斯达克综合', type: 'index' },
    '^NDX': { en: 'NASDAQ 100', cn: '纳斯达克100', type: 'index' },
    '^RUT': { en: 'Russell 2000', cn: '罗素2000', type: 'index' },
    '^VIX': { en: 'VIX', cn: '恐慌指数', type: 'index' },
    '000001.SS': { en: 'SSE Composite', cn: '上证指数', type: 'index' },
    '399001.SZ': { en: 'SZSE Component', cn: '深证成指', type: 'index' },
    '^HSI': { en: 'Hang Seng Index', cn: '恒生指数', type: 'index' },
    '^N225': { en: 'Nikkei 225', cn: '日经225', type: 'index' },
    '^FTSE': { en: 'FTSE 100', cn: '富时100', type: 'index' },
    '^FCHI': { en: 'CAC 40', cn: '法国CAC40', type: 'index' },
    '^GDAXI': { en: 'DAX Performance', cn: '德国DAX', type: 'index' },

    // 2. 美股 (US Stocks)
    'AAPL': { en: 'Apple', cn: '苹果', type: 'us' },
    'MSFT': { en: 'Microsoft', cn: '微软', type: 'us' },
    'GOOGL': { en: 'Alphabet (Google)', cn: '谷歌', type: 'us' },
    'AMZN': { en: 'Amazon', cn: '亚马逊', type: 'us' },
    'NVDA': { en: 'NVIDIA', cn: '英伟达', type: 'us' },
    'TSLA': { en: 'Tesla', cn: '特斯拉', type: 'us' },
    'META': { en: 'Meta (Facebook)', cn: 'Meta', type: 'us' },
    'AMD': { en: 'AMD', cn: '超微半导体', type: 'us' },
    'NFLX': { en: 'Netflix', cn: '奈飞', type: 'us' },
    'INTC': { en: 'Intel', cn: '英特尔', type: 'us' },
    'AVGO': { en: 'Broadcom', cn: '博通', type: 'us' },
    'QCOM': { en: 'Qualcomm', cn: '高通', type: 'us' },
    'TXN': { en: 'Texas Instruments', cn: '德州仪器', type: 'us' },
    'COIN': { en: 'Coinbase', cn: 'Coinbase', type: 'us' },
    'BABA': { en: 'Alibaba', cn: '阿里巴巴', type: 'us' },
    'PDD': { en: 'Pinduoduo', cn: '拼多多', type: 'us' },
    'JD': { en: 'JD.com', cn: '京东', type: 'us' },
    'NIO': { en: 'NIO', cn: '蔚来汽车', type: 'us' },
    'XPEV': { en: 'XPeng', cn: '小鹏汽车', type: 'us' },
    'LI': { en: 'Li Auto', cn: '理想汽车', type: 'us' },

    // 3. A股 (A-Shares)
    '600519.SS': { en: 'Kweichow Moutai', cn: '贵州茅台', type: 'cn' },
    '601398.SS': { en: 'ICBC', cn: '工商银行', type: 'cn' },
    '601288.SS': { en: 'Agricultural Bank', cn: '农业银行', type: 'cn' },
    '300750.SZ': { en: 'CATL', cn: '宁德时代', type: 'cn' },
    '000858.SZ': { en: 'Wuliangye', cn: '五粮液', type: 'cn' },
    '600036.SS': { en: 'China Merchants Bank', cn: '招商银行', type: 'cn' },
    '601318.SS': { en: 'Ping An Insurance', cn: '中国平安', type: 'cn' },
    '002594.SZ': { en: 'BYD', cn: '比亚迪', type: 'cn' },
    '600900.SS': { en: 'China Yangtze Power', cn: '长江电力', type: 'cn' },
    '601857.SS': { en: 'PetroChina', cn: '中国石油', type: 'cn' },
    '600276.SS': { en: 'Hengrui Medicine', cn: '恒瑞医药', type: 'cn' },

    // 4. 加密货币 (Crypto)
    'BTC-USD': { en: 'Bitcoin', cn: '比特币', type: 'crypto' },
    'ETH-USD': { en: 'Ethereum', cn: '以太坊', type: 'crypto' },
    'SOL-USD': { en: 'Solana', cn: '索拉纳', type: 'crypto' },
    'BNB-USD': { en: 'Binance Coin', cn: '币安币', type: 'crypto' },
    'XRP-USD': { en: 'XRP', cn: '瑞波币', type: 'crypto' },
    'DOGE-USD': { en: 'Dogecoin', cn: '狗狗币', type: 'crypto' },
    'ADA-USD': { en: 'Cardano', cn: '卡尔达诺', type: 'crypto' },
    'AVAX-USD': { en: 'Avalanche', cn: '雪崩协议', type: 'crypto' },
    'DOT-USD': { en: 'Polkadot', cn: '波卡币', type: 'crypto' },
    'LINK-USD': { en: 'Chainlink', cn: 'Chainlink', type: 'crypto' },

    // 5. 债券 (Bonds)
    '^TNX': { en: '10-Year Treasury Yield', cn: '10年美债收益率', type: 'bond' },
    '^TYX': { en: '30-Year Treasury Yield', cn: '30年美债收益率', type: 'bond' },
    '^FVX': { en: '5-Year Treasury Yield', cn: '5年美债收益率', type: 'bond' },
    '^IRX': { en: '13-Week Treasury Bill', cn: '13周美债收益率', type: 'bond' },
    'SHY': { en: '1-3 Year Treasury Bond ETF', cn: '1-3年美债ETF', type: 'bond' },
    'IEF': { en: '7-10 Year Treasury Bond ETF', cn: '7-10年美债ETF', type: 'bond' },
    'TLT': { en: '20+ Year Treasury Bond ETF', cn: '20年+美债ETF', type: 'bond' },
    'AGG': { en: 'US Aggregate Bond ETF', cn: '美国综合债券ETF', type: 'bond' },
    'BND': { en: 'Total Bond Market ETF', cn: '全债市ETF', type: 'bond' },
    'LQD': { en: 'Invst Grade Corp Bond ETF', cn: '投资级公司债ETF', type: 'bond' },

    // 6. 期货 (Futures)
    'CL=F': { en: 'Crude Oil', cn: '原油期货', type: 'future' },
    'GC=F': { en: 'Gold', cn: '黄金期货', type: 'future' },
    'SI=F': { en: 'Silver', cn: '白银期货', type: 'future' },
    'NG=F': { en: 'Natural Gas', cn: '天然气期货', type: 'future' },
    'HG=F': { en: 'Copper', cn: '铜期货', type: 'future' },
    'PL=F': { en: 'Platinum', cn: '铂金期货', type: 'future' },
    'PA=F': { en: 'Palladium', cn: '钯金期货', type: 'future' },
    'ZC=F': { en: 'Corn', cn: '玉米期货', type: 'future' },
    'ZS=F': { en: 'Soybean', cn: '大豆期货', type: 'future' },
    'ZW=F': { en: 'Wheat', cn: '小麦期货', type: 'future' },

    // 7. ETF
    'SPY': { en: 'SPDR S&P 500 ETF', cn: '标普500 ETF', type: 'us' },
    'QQQ': { en: 'Invesco QQQ Trust', cn: '纳指100 ETF', type: 'us' },
    'IWM': { en: 'iShares Russell 2000 ETF', cn: '罗素2000 ETF', type: 'us' },
    'DIA': { en: 'SPDR Dow Jones ETF', cn: '道琼斯 ETF', type: 'us' },
    'UVXY': { en: 'ProShares Ultra VIX', cn: '1.5倍做多恐慌指数', type: 'us' },
    'VXX': { en: 'iPath Series B S&P 500 VIX', cn: '短期恐慌指数ETN', type: 'us' },
    'HYG': { en: 'High Yield Corp Bond ETF', cn: '高收益债ETF', type: 'bond' },
    'EEM': { en: 'iShares Emerging Markets ETF', cn: '新兴市场ETF', type: 'us' },
    'FXI': { en: 'iShares China Large-Cap ETF', cn: '中国大盘股ETF', type: 'us' },
};
