"""``backend.app.api.v1.endpoints.analysis`` 包入口。

把 1366 行单文件 ``analysis.py`` 拆为 ``_helpers.py``（analyzer 单例 + 缓存 / 技术
指标 / fallback / 相关性解释 + 本地 CorrelationRequest schema）和 ``routes.py``
（17 个路由 handler）。本 ``__init__`` 重新暴露所有原顶层符号，保持兼容性。
"""

from ._helpers import (
    ANALYSIS_CACHE_TTLS,
    CorrelationRequest,
    _analysis_cache_key,
    _build_klines,
    _build_overview_fallback_response,
    _calculate_bollinger,
    _calculate_macd,
    _calculate_rsi,
    _get_cached_analysis,
    _set_cached_analysis,
    comprehensive_scorer,
    data_manager,
    fundamental_analyzer,
    get_correlation_interpretation,
    logger,
    lstm_predictor,
    model_comparator,
    pattern_recognizer,
    price_predictor,
    sentiment_analyzer,
    trend_analyzer,
    volume_analyzer,
)
from .routes import (
    analysis_overview,
    analyze_correlation,
    analyze_fundamental,
    analyze_sentiment,
    analyze_trend,
    analyze_volume_price,
    compare_model_predictions,
    comprehensive_analysis,
    get_industry_comparison,
    get_klines,
    get_risk_metrics,
    get_sentiment_history,
    get_technical_indicators,
    predict_prices,
    predict_with_lstm,
    recognize_patterns,
    router,
    train_all_models,
)

__all__ = [
    "router",
    "logger",
    # singletons
    "data_manager",
    "trend_analyzer",
    "volume_analyzer",
    "sentiment_analyzer",
    "comprehensive_scorer",
    "pattern_recognizer",
    "fundamental_analyzer",
    "price_predictor",
    "lstm_predictor",
    "model_comparator",
    # helpers
    "ANALYSIS_CACHE_TTLS",
    "CorrelationRequest",
    "_analysis_cache_key",
    "_build_klines",
    "_build_overview_fallback_response",
    "_calculate_bollinger",
    "_calculate_macd",
    "_calculate_rsi",
    "_get_cached_analysis",
    "_set_cached_analysis",
    "get_correlation_interpretation",
    # routes
    "analyze_trend",
    "analyze_correlation",
    "analyze_fundamental",
    "analyze_sentiment",
    "analyze_volume_price",
    "analysis_overview",
    "compare_model_predictions",
    "comprehensive_analysis",
    "get_industry_comparison",
    "get_klines",
    "get_risk_metrics",
    "get_sentiment_history",
    "get_technical_indicators",
    "predict_prices",
    "predict_with_lstm",
    "recognize_patterns",
    "train_all_models",
]
